server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ramanks19/hotel-review-config-server
          clone-on-start: true